"""First mifrations

Revision ID: dfc157c22f88
Revises: c086236d7a87
Create Date: 2023-10-13 12:49:35.957760

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dfc157c22f88'
down_revision = 'c086236d7a87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=140), autoincrement=False, nullable=True),
    sa.Column('slug', sa.VARCHAR(length=140), autoincrement=False, nullable=True),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='blog_pkey'),
    sa.UniqueConstraint('slug', name='blog_slug_key')
    )
    # ### end Alembic commands ###
